=== jamesryanmocorro/modules/weimop/ExportResults.xsd
<!-- edited with XMLSpy v2019 (x64) (http://www.altova.com) by Bogdan Vesovic (SIEMENS INDUSTRY INC. EM DG SW&C SW) -->
<xs:schema xmlns:m="http://www.siemens.com/soa/ExportResults.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.siemens.com/soa/ExportResults.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ExportResults" type="m:ExportResults"/>
	<xs:complexType name="ExportResults">
		<xs:sequence>
			<xs:element name="Database" type="m:Database" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ExportResultsType" type="m:ExportResultsType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Database">
		<xs:sequence>
			<xs:element name="AppDB" type="m:DB"/>
			<xs:element name="ContextInfo" type="m:ContextInfo"/>
			<xs:element name="SOAConnectionPool" type="m:SOAConnectionPool" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DB">
		<xs:sequence>
			<xs:element name="Host" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Port" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Sid" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ContextInfo">
		<xs:sequence>
			<xs:element name="AppSuite" type="xs:string"/>
			<xs:element name="SubAppSuite" type="xs:string"/>
			<xs:element name="FunctionID" type="xs:string"/>
			<xs:element name="Context" type="xs:string"/>
			<xs:element name="ContextXPath" type="xs:string"/>
			<xs:element name="Slot" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SOAConnectionPool">
		<xs:sequence>
			<xs:element name="connpool_min_limit" type="xs:int"/>
			<xs:element name="connpool_max_limit" type="xs:int"/>
			<xs:element name="connpool_increment" type="xs:int"/>
			<xs:element name="connpool_timeout" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ExportResultsType">
		<xs:sequence>
			<xs:element name="Database" type="m:Database" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Query" type="m:Query" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ResultsSummary" type="m:ResultsSummary" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Query">
		<xs:sequence>
			<xs:element name="Select" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="From" type="m:From" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Where" type="m:Where" minOccurs="0" maxOccurs="1"/>
			<xs:element name="OrderBy" type="m:OrderBy" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="From">
		<xs:sequence>
			<xs:element name="Table" type="m:Table" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Table">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Alias" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Where">
		<xs:sequence>
			<xs:element name="Clause" type="m:Clause" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Clause">
		<xs:sequence>
			<xs:element name="Condition" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Operator" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Parameters" type="m:Parameters" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Parameters">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="InputParam" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="StaticParam" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DataType" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Addons" type="m:Addons" minOccurs="0"/>
			<xs:element name="Format" type="m:Format" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Addons">
		<xs:sequence>
			<xs:element name="Functions" type="m:Functions" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Format">
		<xs:sequence>
			<xs:element name="Functions" type="m:Functions" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Functions">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Format" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="source" type="xs:string"/>
		<xs:attribute name="condition" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="OrderBy">
		<xs:sequence>
			<xs:element name="Column" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Option" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultsSummary">
		<xs:sequence>
			<xs:element name="Header" type="m:Header" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Body" type="m:Body" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="RowLimit" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Header">
		<xs:sequence>
			<xs:element name="HeaderElement" type="m:HeaderElement" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HeaderElement">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="DataType" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="DataLength" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Body">
		<xs:sequence>
			<xs:element name="Column" type="m:Column" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Column">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DataType" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="DataLength" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Addons" type="m:Addons" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== jamesryanmocorro/modules/weimop/ExportResultsConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 (x64) (http://www.altova.com) by Bogdan Vesovic (SIEMENS INDUSTRY INC. EM DG SW&C SW) -->
<!--Sample XML file generated by XMLSpy v2017 sp2 (x64) (http://www.altova.com)-->
<m:ExportResults xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://www.siemens.com/soa/ExportResults.xsd" xsi:schemaLocation="http://www.siemens.com/soa/ExportResults.xsd file:///ExportResults.xsd">
	<m:ExportResultsType Name="MPRegionalSummary">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>RUN_TIME</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
					<m:Addons>
						<m:Functions>
							<m:Name>ADD_5MIN</m:Name>
						</m:Functions>
					</m:Addons>
				</m:Column>
				<m:Column>
					<m:Name>MKT_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>REGION_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>COMMODITY_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>2</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MKT_REQT</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>LOAD_BID</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>CURTAILED_LOAD</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MW_LOSSES</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>GENERATION</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MW_IMPORT</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MW_EXPORT</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="MPReserveSchedule">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>RUN_TIME</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MKT_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>RESOURCE_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>128</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>COMMODITY_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>2</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>SCHEDULE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="MPLMP">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>RUN_TIME</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>MKT_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>RESOURCE_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>LMP</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="DIPCLMP">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
					<m:Addons>
						<m:Functions>
							<m:Name>ADD_5MIN</m:Name>
						</m:Functions>
					</m:Addons>
				</m:Column>
				<m:Column>
					<m:Name>RESOURCE_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>AP_FLAG</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>1</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>SEC_FLAG</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>1</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>PSM_FLAG</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>1</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>DIPC_PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>RTD_PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>ADMIN_PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>SEC_PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>PSM_PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="TIPCLMP">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>RESOURCE_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="RTDReserveSchedule">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
					<m:Addons>
						<m:Functions>
							<m:Name>ADD_5MIN</m:Name>
						</m:Functions>
					</m:Addons>
				</m:Column>
				<m:Column>
					<m:Name>RESOURCE_NAME</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>128</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>COMMODITY_TYPE</m:Name>
					<m:DataType>string</m:DataType>
					<m:DataLength>2</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>SCHEDULE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
				<m:Column>
					<m:Name>PRICE</m:Name>
					<m:DataType>double</m:DataType>
					<m:DataLength>32</m:DataLength>
				</m:Column>
			</m:Body>
		</m:ResultsSummary>
	</m:ExportResultsType>
	<m:ExportResultsType Name="RTDSchedules">
		<m:ResultsSummary>
			<m:Header>
				<m:HeaderElement>
					<m:Name>NoOfRows</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
				<m:HeaderElement>
					<m:Name>NoOfColumns</m:Name>
					<m:DataType>int</m:DataType>
					<m:DataLength>4</m:DataLength>
				</m:HeaderElement>
			</m:Header>
			<m:Body>
				<m:Column>
					<m:Name>TIME_INTERVAL</m:Name>
					<m:DataType>long</m:DataType>
					<m:DataLength>32</m:DataLength>
					<m:Addons>
						<m:Functions>
							<m:Name>ADD_5MIN</m:Name>
						</m:Functions>
					</m:Addons>
				</m:Column>
				<m:Column>
